eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.0.240:8761/eureka/
    instance:
      prefer-ip-address: true

ribbon:
  ConnectTimeout: 10000
  ReadTimeout: 10000
  eureka:
    enabled: true
